language: php

php:
 - '7.2'

cache:
  yarn: true

before_script:
 - composer install
 - cp .env.example .env
 - php artisan key:generate
 - phpenv config-rm xdebug.ini


sudo: required
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn install

script:
  - "phpunit"
  - "yarn test"