name: Tests

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.1.0

    - name: Setup PHP 8.3 with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer

    - name: Copy .env
      run: php -r "file_exists('.env.testing') || copy('.env.example', '.env.testing');"
    
    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    
    - name: Install JS Dependencies
      run: yarn install
    
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    
    - name: Generate key
      run: php artisan key:generate --env testing
    
    - name: Execute PHP tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    
    - name: Execute JS tests via Jest
      run: yarn run test
